version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    expose:
      - "16686"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    restart: always
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
#    expose:
#      - "4317"
#      - "4318"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP grpc receiver
      - "4318:4318"   # OTLP Http receiver
      - "55679:55679" # zpages extension
    volumes:
      - "./observability/otel-config.yaml:/etc/otelcol-contrib/config.yaml"
    restart: always
    environment:
      - OTEL_NEW_RELIC_EXPORTER_API_KEY=${OTEL_NEW_RELIC_EXPORTER_API_KEY}
    depends_on:
      - jaeger
  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - ./observability/grafana/provisioning/:/etc/grafana/provisioning/
      - ./observability/grafana/dashboards:/etc/grafana/dashboards
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

volumes:
  grafana_data:
  prometheus_data:
